import Head from 'next/head'
import Banner from '../components/banner/Banner'
import Feed from '../scenes/feed/Feed'

import LandingPage from "../scenes/landingpage"



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main >
        <LandingPage />
        <Banner />
        <Feed />
      </main>
    </>
  )
}
