import axios from 'axios'
import Head from 'next/head'
import { Spinner } from 'react-bootstrap'
import Banner from '../components/banner/Banner'
import Feed from '../scenes/feed/Feed'

import LandingPage from "../scenes/landingpage"
import { getPosts } from '../utils/api'



export default function Home({ data }) {
  const slicedData = data.slice(0, 6)
  if (!data) {
    return <Spinner />
  }
  return (
    <>
      <Head>
        <title>Blog </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main >
        <LandingPage />
        <Banner />
        <Feed data={slicedData} />
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const data = await getPosts()
  if (!data) {
    return {
      notFound: true
    }
  }
  return {
    props: {
      data
    }
  }
}